server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: mangas-service 
              uri: lb://mangas
              predicates:
                - Path=/api/v1/mangas/**, /api/v1/demografias/**, /api/v1/inventarios/**, /mangas/api-docs

            - id: autores-service
              uri: lb://autores
              predicates:
                - Path=/api/v1/autores/**, /api/v1/generos/**, /api/v1/origenes/**, /autores/api-docs

            - id: usuarios-service
              uri: lb://usuarios
              predicates:
                - Path=/api/v1/usuarios/**, /api/v1/carritos/**, /api/v1/pagos/**, /api/v1/resenas/**, /usuarios/api-docs
            
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Microservicio Mangas
        url: /mangas/api-docs
      - name: Microservicio Autores
        url: /autores/api-docs
      - name: Microservicio Usuarios
        url: /usuarios/api-docs